pipeline_space:
  num_layers:
    lower: 2
    upper: 4
  num_neurons:
    lower: 32
    upper: 256
  batch_size:
    lower: 32
    upper: 1024
  learning_rate:
    lower: 0.0001
    upper: 0.1
    log: true
  weight_decay:
    lower: 0.0001
    upper: 0.1
    log: true
  optimizer:
    choices: ["adamw", "adam", "sgd"]
  epochs:
    lower: 1
    upper: 10
    is_fidelity: true

run_pipeline:
  path: ./hpo_target.py
  name: training_pipeline

searcher: hyperband

root_directory: ./neps_debug/hb
max_evaluations_total: 50
post_run_summary: true
overwrite_working_directory: false